//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDW.ServiceGeneraToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicio.org/", ConfigurationName="ServiceGeneraToken.GeneradorToken")]
    public interface GeneradorToken {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio.org/GeneradorToken/getTokenRequest", ReplyAction="http://servicio.org/GeneradorToken/getTokenResponse")]
        ProyectoDW.ServiceGeneraToken.getTokenResponse getToken(ProyectoDW.ServiceGeneraToken.getTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio.org/GeneradorToken/getTokenRequest", ReplyAction="http://servicio.org/GeneradorToken/getTokenResponse")]
        System.Threading.Tasks.Task<ProyectoDW.ServiceGeneraToken.getTokenResponse> getTokenAsync(ProyectoDW.ServiceGeneraToken.getTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getToken", Namespace="http://servicio.org/", Order=0)]
        public ProyectoDW.ServiceGeneraToken.getTokenRequestBody Body;
        
        public getTokenRequest() {
        }
        
        public getTokenRequest(ProyectoDW.ServiceGeneraToken.getTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int mes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int anio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cvv;
        
        public getTokenRequestBody() {
        }
        
        public getTokenRequestBody(string nombre, string numeroTarjeta, int mes, int anio, string cvv) {
            this.nombre = nombre;
            this.numeroTarjeta = numeroTarjeta;
            this.mes = mes;
            this.anio = anio;
            this.cvv = cvv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTokenResponse", Namespace="http://servicio.org/", Order=0)]
        public ProyectoDW.ServiceGeneraToken.getTokenResponseBody Body;
        
        public getTokenResponse() {
        }
        
        public getTokenResponse(ProyectoDW.ServiceGeneraToken.getTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTokenResponseBody() {
        }
        
        public getTokenResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneradorTokenChannel : ProyectoDW.ServiceGeneraToken.GeneradorToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneradorTokenClient : System.ServiceModel.ClientBase<ProyectoDW.ServiceGeneraToken.GeneradorToken>, ProyectoDW.ServiceGeneraToken.GeneradorToken {
        
        public GeneradorTokenClient() {
        }
        
        public GeneradorTokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneradorTokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneradorTokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneradorTokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoDW.ServiceGeneraToken.getTokenResponse ProyectoDW.ServiceGeneraToken.GeneradorToken.getToken(ProyectoDW.ServiceGeneraToken.getTokenRequest request) {
            return base.Channel.getToken(request);
        }
        
        public string getToken(string nombre, string numeroTarjeta, int mes, int anio, string cvv) {
            ProyectoDW.ServiceGeneraToken.getTokenRequest inValue = new ProyectoDW.ServiceGeneraToken.getTokenRequest();
            inValue.Body = new ProyectoDW.ServiceGeneraToken.getTokenRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.mes = mes;
            inValue.Body.anio = anio;
            inValue.Body.cvv = cvv;
            ProyectoDW.ServiceGeneraToken.getTokenResponse retVal = ((ProyectoDW.ServiceGeneraToken.GeneradorToken)(this)).getToken(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoDW.ServiceGeneraToken.getTokenResponse> ProyectoDW.ServiceGeneraToken.GeneradorToken.getTokenAsync(ProyectoDW.ServiceGeneraToken.getTokenRequest request) {
            return base.Channel.getTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoDW.ServiceGeneraToken.getTokenResponse> getTokenAsync(string nombre, string numeroTarjeta, int mes, int anio, string cvv) {
            ProyectoDW.ServiceGeneraToken.getTokenRequest inValue = new ProyectoDW.ServiceGeneraToken.getTokenRequest();
            inValue.Body = new ProyectoDW.ServiceGeneraToken.getTokenRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.mes = mes;
            inValue.Body.anio = anio;
            inValue.Body.cvv = cvv;
            return ((ProyectoDW.ServiceGeneraToken.GeneradorToken)(this)).getTokenAsync(inValue);
        }
    }
}
