//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDW.ServiceInsertTransaccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicio.org/", ConfigurationName="ServiceInsertTransaccion.InsertarTransaccion")]
    public interface InsertarTransaccion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio.org/InsertarTransaccion/ingresarTransaccionRequest", ReplyAction="http://servicio.org/InsertarTransaccion/ingresarTransaccionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse ingresarTransaccion(ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio.org/InsertarTransaccion/ingresarTransaccionRequest", ReplyAction="http://servicio.org/InsertarTransaccion/ingresarTransaccionResponse")]
        System.Threading.Tasks.Task<ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse> ingresarTransaccionAsync(ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio.org/")]
    public partial class modelTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string autorizacionField;
        
        private int estadoTransaccionField;
        
        private string estadoTransaccionsField;
        
        private int idTransaccionField;
        
        private double montoField;
        
        private string nombreField;
        
        private string ultimosDitigosTarjetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
                this.RaisePropertyChanged("autorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int estadoTransaccion {
            get {
                return this.estadoTransaccionField;
            }
            set {
                this.estadoTransaccionField = value;
                this.RaisePropertyChanged("estadoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoTransaccions {
            get {
                return this.estadoTransaccionsField;
            }
            set {
                this.estadoTransaccionsField = value;
                this.RaisePropertyChanged("estadoTransaccions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ultimosDitigosTarjeta {
            get {
                return this.ultimosDitigosTarjetaField;
            }
            set {
                this.ultimosDitigosTarjetaField = value;
                this.RaisePropertyChanged("ultimosDitigosTarjeta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ingresarTransaccion", WrapperNamespace="http://servicio.org/", IsWrapped=true)]
    public partial class ingresarTransaccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ultimosDitigosTarjeta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoTransaccion;
        
        public ingresarTransaccionRequest() {
        }
        
        public ingresarTransaccionRequest(int idTransaccion, string ultimosDitigosTarjeta, string nombre, string autorizacion, double monto, int estadoTransaccion) {
            this.idTransaccion = idTransaccion;
            this.ultimosDitigosTarjeta = ultimosDitigosTarjeta;
            this.nombre = nombre;
            this.autorizacion = autorizacion;
            this.monto = monto;
            this.estadoTransaccion = estadoTransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ingresarTransaccionResponse", WrapperNamespace="http://servicio.org/", IsWrapped=true)]
    public partial class ingresarTransaccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoDW.ServiceInsertTransaccion.modelTransaccion @return;
        
        public ingresarTransaccionResponse() {
        }
        
        public ingresarTransaccionResponse(ProyectoDW.ServiceInsertTransaccion.modelTransaccion @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InsertarTransaccionChannel : ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertarTransaccionClient : System.ServiceModel.ClientBase<ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion>, ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion {
        
        public InsertarTransaccionClient() {
        }
        
        public InsertarTransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertarTransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertarTransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertarTransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion.ingresarTransaccion(ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest request) {
            return base.Channel.ingresarTransaccion(request);
        }
        
        public ProyectoDW.ServiceInsertTransaccion.modelTransaccion ingresarTransaccion(int idTransaccion, string ultimosDitigosTarjeta, string nombre, string autorizacion, double monto, int estadoTransaccion) {
            ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest inValue = new ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest();
            inValue.idTransaccion = idTransaccion;
            inValue.ultimosDitigosTarjeta = ultimosDitigosTarjeta;
            inValue.nombre = nombre;
            inValue.autorizacion = autorizacion;
            inValue.monto = monto;
            inValue.estadoTransaccion = estadoTransaccion;
            ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse retVal = ((ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion)(this)).ingresarTransaccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse> ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion.ingresarTransaccionAsync(ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest request) {
            return base.Channel.ingresarTransaccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionResponse> ingresarTransaccionAsync(int idTransaccion, string ultimosDitigosTarjeta, string nombre, string autorizacion, double monto, int estadoTransaccion) {
            ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest inValue = new ProyectoDW.ServiceInsertTransaccion.ingresarTransaccionRequest();
            inValue.idTransaccion = idTransaccion;
            inValue.ultimosDitigosTarjeta = ultimosDitigosTarjeta;
            inValue.nombre = nombre;
            inValue.autorizacion = autorizacion;
            inValue.monto = monto;
            inValue.estadoTransaccion = estadoTransaccion;
            return ((ProyectoDW.ServiceInsertTransaccion.InsertarTransaccion)(this)).ingresarTransaccionAsync(inValue);
        }
    }
}
